### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fdaciuk** [braziljs/braziljs-conf#15]
Fala povo! O site desse ano ficou muito bom, parabéns :D 
Encontrei alguns errinhos de pt-br, vou colar os links aqui (os fontes não estão nesse repo né? xD):

https://github.com/braziljs/braziljs-conf/blob/gh-pages/index.html#L1291
Está escrito **páginias**. Deveria ser **páginas**.

https://github.com/braziljs/braziljs-conf/blob/gh-pages/index.html#L598
Está escrito `<S></S>erviu`. Deveria ser **Serviu**.

:dancer: :dancer:

**Comment by jaydson** [comment]
Valeu @fdaciuk !

**Comment by fdaciuk** [comment]
o/
